### ISSUE TITLE
Support any virtual env manager

### ISSUE THREAD

**Issue by vsriram11** [databrickslabs/jupyterlab-integration#10]
The package relies on conda, but conda is very heavyweight and not everyone is a huge conda fan. 

I believe this is a lower priority issue, but it would be great if we could use any virtual env manager we want, like say Poetry.

**Comment by bernhard-42** [comment]
hmm, agreed, that would be nice, however, conda is pretty much baked into it at the moment. And it needs to run on *nix and Windows (since v2 will have native Windows support) and I don't know too much about other env managers and their support of Windows.

I'm not sure I will find time soon to encapsulate the env manager part and support more than conda ... but I'll keep it on the todo list.

**Comment by TeraInferno** [comment]
I personally use `pyenv` and `pyenv-virtualenv` as my Python installation and virtual env manager. It tends to work out pretty darn well. I do quite a bit of python development, and it ranges from basic local scripts to Flask web applications to backend API servers to notebooks. However, adding Conda into that mix causes problems. 

I setup my environment like so:
```bash
#!/usr/bin/env bash

# Setup Python
pyenv install 3.7.3
pyenv virtualenv 3.7.3 Databricks-6.6
pyenv activate Databricks-6.6

# Upgrade pip and setuptools
pip install --upgrade pip
pip install --upgrade setuptools

# Add basics
pip install numpy pandas matplotlib
pip install jupyter jupyterlab

#  Usefull utilities and stuff
pip install requests sqlalchemy

# Add Databricks
pip install pypandoc
pip install databricks-connect==6.6
pip install databricks-cli

# Write requirements file
pip freeze >! requirements.txt
```

I would love to use this jupyter lab integration myself, but I would like to avoid anaconda if possible too.

**Comment by bernhard-42** [comment]
I thought longer about it and the efforts to support other env managers are too high.
So I will keep with Anaconda for the time being and focus on other features like "notebook scoped libraries"
Maybe some time in the future I might reconsider ...
