### ISSUE TITLE
Matplotlib and plotly plots don't render

### ISSUE THREAD

**Issue by vsriram11** [databrickslabs/jupyterlab-integration#11]
Dataframes render fine in local Jupyter notebook, but matplotlib and plotly plots do not.

For matplotlib, the plot simply does not render:

![image](https://user-images.githubusercontent.com/3003836/82408825-6e728100-9a3a-11ea-9009-d9b6e58b2d33.png)

For plotly, the error when using default plotly renderer is

![image](https://user-images.githubusercontent.com/3003836/82408909-92ce5d80-9a3a-11ea-8a34-405aac2eb01f.png)

When updating the default render to "notebook", nothing is printed out, similar to matplotlib. I can make plotly work with a very hacky workaround, by saving the plot as HTML and then displaying the HTML.

**Comment by bernhard-42** [comment]
Hi @vsriram11 
For matplotlib, could you try `%matplotlib inline`
![image](https://user-images.githubusercontent.com/954408/82409905-0d18d500-9a6f-11ea-8f11-6e1aaa900fb9.png)

**Comment by bernhard-42** [comment]
And for plotly, one currently needs the following `displayHTML` function:

```python
from IPython.display import display, HTML
def displayHTML(*args):
    display(HTML(*args))
```

Then:

![image](https://user-images.githubusercontent.com/954408/82410670-a0063f00-9a70-11ea-9d01-4729e52f6c0c.png)

`displayHTML`is missing, this is a bug and will be fixed in the next version (which will be a major version v2, out in the next two weeks)

**Comment by vsriram11** [comment]
Thanks for the quick reply! Yes, this works for matplotlib. For plotly, this simple example works, but I'm still having issues with more advanced examples.

The plotly/ipython widget integration doesn't work, for example. Using plotly with ipython widgets was actually my original intention in wanting to use the Databricks-JupyetLab integration - perform data science EDA with plotly and ipythonwidgets.

Running the example in https://plotly.com/python/figurewidget-app/, will result in the following error -

![image](https://user-images.githubusercontent.com/3003836/82450906-49523280-9a7b-11ea-87d2-5dec38cd5852.png)

**Comment by bernhard-42** [comment]
@vsriram11 
"model not found" usually means that the plotly is not properly installed.
Initially I had forgotten `plotlywidget` and also got a "model not found error"

It works for me after installing both
```bash
jupyter labextension install jupyterlab-plotly@4.7.1
jupyter labextension install plotlywidget@4.7.1
```
with the latest version 4.7.1 of plotly

**Comment by vsriram11** [comment]
Amazing - thanks for the help, and great work with this library. This all works fine now, closing the issue :)
