### ISSUE TITLE
DBR 7.3 version support

### ISSUE THREAD

**Issue by ankitbko** [databrickslabs/jupyterlab-integration#18]
Readme mentions we support DBR 7.0 beta. Is 7.3 ML LTS also supported?

**Comment by bernhard-42** [comment]
@ankitbko Yes, it does work with all 7.x versions, also in particular with 7.3 LTS. I just tested 7.5, it also works.
I need to update the Readme, thanks for the notification (when this version came out, only 7.0 was available).
