### ISSUE TITLE
Custom environment variables for kernels

### ISSUE THREAD

**Issue by apulich-exos** [databrickslabs/jupyterlab-integration#19]
Hi! 
Firstly, Thank you for your work!

I'm wondering If I can somehow specify custom environment variables for my ssh kernel. 
I have some custom libraries for which I need to specify PYTHONPATH, LD_LIBRARY_PATH and some other env vars. When I just use simple Databricks notebooks I have my own docker image and Init Scripts where I setup these vars and add them to .bashrc. But if I run Jupyterlab with databricks integration then I don't see those variables. The only workaround I've found so far is to edit local.py from this library and setup my env [there](https://github.com/databrickslabs/jupyterlab-integration/blob/2818b8153360f7dd6a0a986f42fd78d89f0a024c/databrickslabs_jupyterlab/local.py#L209). 
Obviously, this is a rather dirty hack.

**Comment by bernhard-42** [comment]
@apulich-exos Currently "dj -k" does not support that from the command line.
However, the underlying `ssh_ipykernel` does, so one option would be to edit `kernel.json` after `dj -k` and add the variables (e.g. `MYVAR=/my/path`) to the `--env` flag

```json
{
  "argv": [
    "/opt/miniconda/envs/db-jlab/bin/python",
    "-m",
    "databrickslabs_jupyterlab",
    "--host",
    "0123-456789-abcde",
    "--python",
    "/databricks/python",
    "--timeout",
    "5",
    "--env",
    "MYVAR=/my/path DBJL_PROFILE=aws-ffm DBJL_HOST=https://dbc-123456789-abcd.cloud.databricks.com DBJL_CLUSTER=0123-456789-abcde",
    "-s",
    "-f",
    "{connection_file}"
  ],
  "display_name": "SSH 0123-456789-abcde aws-ffm:test75 (db-jlab/Spark)",
  "language": "python"
}
```

However, this needs to be done every time you call `dj -k`. 
I will add a flag to `dj` in the next release. Until then, would the `kernel.json` trick (maybe automated by a line of `sed` if you are on a unix based system) help?

**Comment by apulich-exos** [comment]
Thank you @bernhard-42
I will stay with your workaround for now.

**Comment by bernhard-42** [comment]
@apulich-exos As you can see from the master Readme.md, there is a release candidate out that supports your env issue and solves the multiline config bug. Maybe you could give it a try whether it works for you. With the release version coming soon I will also push a new docker container (currently only the conda way works).

**Comment by apulich-exos** [comment]
Great, thank you. I'll check it today and will get back with a feedback. Conda way is enough.

**Comment by apulich-exos** [comment]
@bernhard-42 works perfectly! Thank you a lot.

**Comment by bernhard-42** [comment]
@apulich-exos 
The lastest release (April) also supports a new flag `-e` for the `dj` command to set additional variables that appear in Databricks:
`dj westeu -k -e MY_VAR1=42 SCHNADDEL=DADDEL`:

![image](https://user-images.githubusercontent.com/954408/121674509-70c6d380-cab2-11eb-8c34-ffd353fa0f0b.png)

**Comment by apulich-exos** [comment]
Great, thank you a lot!
