### ISSUE TITLE
Upgrade notebook to latest version 6.2.0

### ISSUE THREAD

**Issue by prabdeb** [databrickslabs/jupyterlab-integration#23]
Is it possible to upgrade notebook to latest version 6.2.0?

In the used version of jupyter/notebook (notebook==6.0.3) there is a problem with `Ensure that cell ids persist after save`, [discussed PR in jupyter/notebook](https://github.com/jupyter/notebook/pull/5928). Which has been fixed in notebook [in latest version 6.2.0](https://jupyter-notebook.readthedocs.io/en/stable/changelog.html#release-6-2-0). Without this whenever we save Notebook it will create new ID for each cell and review on Notebook becomes difficult.

I was checking if there is any possibility to upgrade notebook to latest version 6.2.0, your help will be appreciated!

**Comment by bernhard-42** [comment]
@prabdeb Apologies, I completely forgot about replying to this issue.
The release of April 21st now uses JupyterLab 3 and notebook 6.3
I hope this helps.

**Comment by bernhard-42** [comment]
Closing for now. If there are still issues please reopen
