### ISSUE TITLE
After I pip install, but I encounter ModuleNotFoundError: No module named 'version_parser'

### ISSUE THREAD

**Issue by nelsontseng0704** [databrickslabs/jupyterlab-integration#31]
Hi Databricks,

After I pip install --upgrade databrickslabs-jupyterlab==2.2.1, but encounter encounter ModuleNotFoundError: No module named 'version_parser'. 

Where I can find the version_parser to install??

Best,

**Comment by bernhard-42** [comment]
@nelsontseng0704 Please use `pip install --upgrade databrickslabs-jupyterlab[cli]==2.2.1` to install it (note the trailing  `[cli]`), see https://github.com/databrickslabs/jupyterlab-integration#5-local-installation

Otherwise you only install the server side part which doesn't have dependencies

**Comment by nelsontseng0704** [comment]
Thanks for the reply. I try " pip install --upgrade databrickslabs-jupyterlab[cli]==2.2.1" but, it returns

```
(dj) nelsonXXXXX@Nelsons-MBP jupyterlab-integration % pip install --upgrade databrickslabs-jupyterlab[cli]==2.2.1
zsh: no matches found: databrickslabs-jupyterlab[cli]==2.2.1
```
And my pip version is 21.0.1

**Comment by nelsontseng0704** [comment]
I change into pip install --upgrade 'databrickslabs-jupyterlab[cli]==2.2.1' and the pip install successfully done.
