### ISSUE TITLE
Cluster not reachable exception

### ISSUE THREAD

**Issue by bradshawben** [databrickslabs/jupyterlab-integration#5]
First off just want to say I think this tool is great, and generally works flawlessly. I'm running into an issue where i'll sporadically receive a "Cluster Unreachable" exception, prompting me to restart the cluster. For long running jobs, this is can be annoying, since it forces me to restart the cluster, and then re kick off the job. Any ideas why this is happening? It happens even in the middle of interactive work where my local machine is active and (in theory) the SSH tunnel is stable (although I haven't tested network disruptions etc).

Here's the pop up that will surface:
![image](https://user-images.githubusercontent.com/13699936/73486096-4101aa80-4359-11ea-9503-fcc638638446.png)

Any help is much appreciated.

**Comment by bernhard-42** [comment]
Hi @bradshawben,
I have seen a similar behaviour, when I left my laptop and it actually sent the network to sleep and cut off the connection. I solved it by preventing my laptop from deep sleeping (Amphetamine or similar on the Mac). You can then still lock the screen (for security reasons), but the ssh connection stays available.

Another idea would be about the version you run. I had a bug in one of the earlier versions that the ssh config was wrong. Actually it should be something like:

```text
Host my-server
    HostName my-server
    User bernhard
    Port 22
    IdentityFile ~/.ssh/id_rsa
    ServerAliveInterval 30
    ServerAliveCountMax 5760
```
Important are the `Alive` variables. they should keep ssh to ignore networks issues for up to 48h.
In older versions these values were much too low.

**Comment by bradshawben** [comment]
@bernhard-42 I checked the generated config files but they seem to be correct as per your specifications outlined above. I'll keep troubleshooting and circle back if I can diagnose anything definitive. Thanks again for the help!

**Comment by bernhard-42** [comment]
If you still have issues, please reopen
