### ISSUE TITLE
Would using the Windows Subsystem for Linux be a potential workaround for the lack of Windows support?

### ISSUE THREAD

**Issue by KevinXTian** [databrickslabs/jupyterlab-integration#6]
As mentioned in the document, `Either Macos or Linux. Windows is currently not supported`. What about Windows Subsystem for Linus?

**Comment by bernhard-42** [comment]
@KevinXTian This is actually a great idea, so I gave it a try.
I installed WSL + ubuntu, followed the Jupyterlab Integration Readme and after starting jupyter lab in WSL, I connected from Windows installed browser to localhost:8888 - and it worked!
![image](https://user-images.githubusercontent.com/954408/75044391-d9ef9580-54c1-11ea-8da1-020cc457a1de.png)

I will document it as a workaround.

Side note: reason for not supporting Windows at the moment is that pexpect's pxssh (i.e. pexpect.spawn) is not supported and I would need to write a complete different remote access module for it. Might come some day, but for the time being there wasn't so much of a pull for windows ...

**Comment by bernhard-42** [comment]
@KevinXTian For your info, I will soon publish version 2 which has native windows support.

**Comment by KevinXTian** [comment]
Thanks for the update and looking forward to that

________________________________

**Comment by bernhard-42** [comment]
@KevinXTian 
fyi, I today launched V2.0.0. It supports Windows in two ways:
- natively with anaconda and JupyterLab installed on Windows 10 (dj.bat will be installed)
- with docker (dk-dj.bat and dk-jupyter.bat are part of the repo)

**Comment by bernhard-42** [comment]
I will close this since Windows is officially supported now.
