### ISSUE TITLE
local.py line 125 IndexError: list index out of range

### ISSUE THREAD

**Issue by ninghaocalgary** [databrickslabs/jupyterlab-integration#7]
Hello, all: trying to set up following the instruction on Azure Databricks getting this error, 
```
databrickslabs-jupyterlab eastus -k -i 0426-155413-ring996
Traceback (most recent call last):
  File "/data/anaconda/envs/db-jlab/bin/databrickslabs-jupyterlab", line 171, in <module>
    version = conda_version()
  File "/data/anaconda/envs/db-jlab/lib/python3.6/site-packages/databrickslabs_jupyterlab/local.py", line 125, in conda_version
    return result["stdout"].strip().split(" ")[1]
IndexError: list index out of range
```
I am able to SSH into master no problem. 
-p also list the profile.
```
databrickslabs-jupyterlab -p

PROFILE              HOST                                                         SSH KEY
eastus               https://eastus.azuredatabricks.net/?o=3573392022285404       OK
```
databricks cli connects with cluster successful.
```
databricks clusters list --profile eastus
0426-155413-ring996   gpu  RUNNING
0404-233454-navel281  std  TERMINATED
```
Much appreciated on your help.

**Comment by bernhard-42** [comment]
Hi @ninghaocalgary 
Could you please post the output of your `conda --version` in your environment?
Thanks

**Comment by ninghaocalgary** [comment]
conda 4.7.12 
Thanks, Bernhard-42.

**Comment by bernhard-42** [comment]
hmmm that looks ok. 

If I call:

```python
from databrickslabs_jupyterlab.local import execute
execute(["conda", "--version"])
```

I receive:
```
{'args': ['conda', '--version'],
 'returncode': 0,
 'stdout': 'conda 4.8.0\n',
 'stderr': ''}
```

which works well with the line `result["stdout"].strip().split(" ")[1]` in the error message.

Could you please execute the two lines above and post the result. I don't know what is different for you at the moment

**Comment by ninghaocalgary** [comment]
{'args': ['conda', '--version'], 'returncode': 0, 'stdout': '', 'stderr': 'conda 4.7.12\n'}

mmm. stdout is empty and stderr has version..... tweaked my local code, works now. Thanks, :).

**Comment by bernhard-42** [comment]
Interesting, I need to look into that.
Great that you are unblocked now. I will take this issue into account for the new version.
Thank you!

**Comment by bernhard-42** [comment]
@ninghaocalgary 
fyi, I just today launched the newest major release V2.0.0 which should have fixed this. I just now check both stdout and stderr whether they start with "conda"

**Comment by bernhard-42** [comment]
I will close this. If it is still an issue for you, please feel free to open again
