### ISSUE TITLE
Missing arguments error on getting Spark context

### ISSUE THREAD

**Issue by wajatimur** [databrickslabs/jupyterlab-integration#8]
I'm getting a missing arguments error of 'pinned_mode' upon successful connect when I tried to get the Spark context.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-376bcb4d28bb> in <module>
      1 from databrickslabs_jupyterlab.connect import dbcontext, is_remote
----> 2 dbcontext()

/databricks/python/lib/python3.7/site-packages/databrickslabs_jupyterlab/connect.py in dbcontext(progressbar)
    179     # ... and connect to this gateway
    180     #
--> 181     gateway = get_existing_gateway(port, True, auth_token)
    182     print(". connected")
    183     # print("Python interpreter: %s" % interpreter)

TypeError: get_existing_gateway() missing 1 required positional argument: 'pinned_mode'
```

**Comment by bernhard-42** [comment]
@wajatimur This is a known issue at the moment. It appeared wit DBR 6.4. Would it be possible to use DBR 6.3 for the rime being?
I am planning to release a new major release in the next two weeks (final testing phase) which will fix this too

**Comment by wajatimur** [comment]
@bernhard-42 thanks for the clarification, will close the issue for now.

**Comment by vsriram11** [comment]
@wajatimur I ran into this issue as well, and installing the prerelease version fixed it for me (if you need to unblock yourself now instead of waiting 2 weeks for stable release).

**Comment by wajatimur** [comment]
Thanks for the suggestion @vsriram11 , so far it doesn't have any major operational impact.

**Comment by bernhard-42** [comment]
@vsriram11 @wajatimur 
Just for information, V2.0.0 is published
